#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
BEGIN { unshift @INC, "$FindBin::Bin/../lib" }

require Mojolicious::Commands;
Mojolicious::Commands->start_app('Cryostatic');

__END__

=head1 NAME

cryostatic - datacode ngin.

=head1 DESCRIPTION

The scripts entry point.

=cut
